name: windows-build

on:
  workflow_dispatch:
  push:
    paths:
    - .github/workflows/windows.yml
    - src
    - build.sh
    - run.sh

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Fix STXXL
        run: |
          sed -i '25d' external/stxxl/include/stxxl/bits/msvc_compatibility.h
          sed -i '24d' external/stxxl/include/stxxl/bits/msvc_compatibility.h
          sed -i '23d' external/stxxl/include/stxxl/bits/msvc_compatibility.h
          sed -i '22d' external/stxxl/include/stxxl/bits/msvc_compatibility.h
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../src/ -G "Visual Studio 17 2022" 
          cmake --build . --config Release
      #- name: Run
        #run: |
          #./run.sh
